### ISSUE TITLE
最近也在做DW1000的项目，求交流，求指导，急～

### ISSUE THREAD

**Issue by hANSONxIE** [BUPTUWB/dw1000_firmware#4]
你好，刚刚看了代码，感觉很不错呢
可是我对于DW1000不怎么熟悉，datasheet又是全英，呜呜

**Comment by lixin9311** [comment]
对不起，商业支持肯定是要服务费的。
如果你想用明白，手册必须要看的。

**Comment by hANSONxIE** [comment]
不算是商业项目，跟同学做毕业设计
可以加QQ私聊吗？ 我有几个寄存器看得不太懂，希望能交流交流 ：）
