### ISSUE TITLE
项目交流

### ISSUE THREAD

**Issue by zhyinch** [BUPTUWB/dw1000_firmware#5]
你好，我也是北邮的学生。最近在做DW1000定位相关的项目，对你们做的很感兴趣，希望可以交流下，我的QQ：634916154，加下我吧。

**Comment by ghost** [comment]
你好，我也在做dw1000的开发，我想问下你分享的这个定位系统稳定吗？会不会死机呢？

**Comment by zhyinch** [comment]
你好，我最近把官方的例程在自己的板子上跑通了，有问题的话可以交流一下，我QQ号在上面。

**Comment by ghost** [comment]
嗯，我刚加了你，你QQ需要验证信息

**Comment by zhyinch** [comment]
你好，我改好了，你再加一次吧

**Comment by ghost** [comment]
我已经加了你了
